# Stereo -> PointCloud2 + AI Inference node parameters:
inference_stereo_node:
  ros__parameters:
    verbose: True        # If true - print debug info.
    log_every_n_packets: 10     # 0 for no log
    calibration_file: '/home/ros/robot_ws/install/ros2_inference_stereo/share/ros2_inference_stereo/config/calib_820x616.npz'
    scale_factor: 1.0  # 1.0 = full resolution, 0.5 = half resolution, etc. for stereo disparity and pointcloud processing
    model_path: 'models/yolo11n.pt'  # relative to where you launch, e.g. "~/robot_ws/models/yolo11n.pt"
    #image_topic: 'camera/image_raw/compressed'   # for bounding boxes overlay preview in RViz2, saves WiFi traffic
    image_topic: 'camera/image_raw'  # for bounding boxes overlay preview in RViz2, if uncompressed images are preferred
    jpeg_quality: 80                 # JPEG quality for compressed image output (1-100, higher is better quality and larger size)
    camera_info_topic: 'camera/camera_info'
    depth_image_topic: 'stereo/depth/image_rect_raw'  # Empty string disables depth image publishing
    cloud_topic: 'stereo/sparse_cloud'                # Empty string disables sparse pointcloud publishing
    detection_topic: 'image_inference_detections'     # Empty string disables detections publishing
    frame_id: 'camera_stereo_link_optical'   # must be consistent with your robot's camera link on TF tree
    grid_size: 16  # Grid size NxN for sparse sampling
    close_cutout_factor: 1.0
    far_smoothing_factor: 1.0
    color_patch_fraction: 0.5   # center patch size relative to cell
    use_mean_color: True
    min_valid_disp: 1.0
    min_disp_confidence: 0.02   # do not publish if stereo disparity confidence is below this threshold
    pointcloud_delay_sec: 0.02  # short "sleep" after pointcloud processing to free CPU
    detect_delay_sec: 0.02      # short "sleep" after detections processing to free CPU
    # inference related:
    min_confidence: 0.6         # object detection confidence threshold
    objects_allowed: ['']       # Empty list means allow all detected objects.
    #objects_allowed: ['person', 'cup', 'bottle', 'cell phone', 'banana', 'book', 'scissors', 'dog', 'cat']  # Not case sensitive.

# Stereo -> Depth Image for RTAB-Map node parameters:
stereo_node:
  ros__parameters:
    verbose: True        # If true - print debug info.
    calibration_file: '/home/ros/robot_ws/install/ros2_inference_stereo/share/ros2_inference_stereo/config/calib_820x616.npz'
    scale_factor: 0.5  # 1.0 = full resolution, 0.5 = half resolution, etc. for stereo disparity and pointcloud processing
    image_topic: 'camera/image_raw'  # for overlay preview, uncompressed
    camera_info_topic: 'camera/camera_info'
    depth_image_topic: 'stereo/depth/image_rect_raw'
    frame_id: 'camera_stereo_link_optical'   # must be consistent with your robot's camera link on TF tree
    close_cutout_factor: 1.0
    far_smoothing_factor: 1.0
    min_valid_disp: 1.0
    loop_delay_sec: 0.05      # short "sleep" after processing to free CPU

# Perception adapter (BT topics relay) configuration
perception_adapter:
  ros__parameters:
    verbose: True        # If true - print debug info about recognized and passed detections.
    ticker_interval_sec: 0.1
    detection_topic: 'image_inference_detections'
    #face_detected_sound: 'my_face.wav'
    face_detected_text: 'I see you!'
    min_confidence: 0.6  # object detection confidence threshold
    face_cooldown_sec: 2.0
    gesture_cooldown_sec: 1.0
    camera_center_x: 320.0  # Assuming 640x480 input images. Adjust if different.
    target_label: 'person'  # The "face detected" logic is applied only to this object class.
    # Optional mapping of incoming class labels to "normalized class labels". Normally is not needed:
    label_map_json: '{}'  # example: {"0":"person","1":"cat","cup_small":"cup"}',
    # Optional JSON string mapping object labels to "gestures". If not set, capitalized label will be used:
    gesture_map_json: '{"bottle":"STOP", "cup":"OK", "banana":"LIKE", "cat":"MEOW", "dog":"WOOF"}'
    # Optional JSON string mapping gestures/commands to speech output. If not set, the gesture name will be used:
    speech_map_json: '{"STOP":"Stop immediately!","OK":"good stuff!","scissors":"Careful, sharp!","FIRE_HYDRANT":"Fire hydrant - do not park!"}'

detection_visualizer:
  ros__parameters:
    verbose: False        # If true - print debug info
    image_topic: 'camera/image_raw/compressed'  # or "camera/image_raw", make sure it matches what inference_stereo_node publishes
    detection_topic: 'image_inference_detections'
    overlay_image_topic: 'camera/image_inference_overlay'  # topic to publish overlay visualization (bounding boxes etc.) for RViz2 preview
    time_slop: 0.01       # "self.time_slop" defines tolerance to header timestamps when synchronizing images and detections
